### ISSUE TITLE
Trouble building in VS2017

### ISSUE THREAD

**Issue by RallyTronics** [mizvekov/fp#1]
I am just wondering if anyone has this working under VS2017, I am unable to build without a number of errors.

I am attempting to compile

    auto x = make_fp<int64_t, 32 >(3.25);
    auto y = make_fp<int64_t, 32>(0.75);
    auto z = x * y;                
    std::cout << double(z);  

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2893	Failed to specialize function template 'unknown-type std::multiplies<void>::operator ()(_Ty1 &&,_Ty2 &&) const'	fixed_point	f:\mtsbx\fp\fp.hpp	186	
Error	C2893	Failed to specialize function template 'auto fp::fp_t<int64_t,32,A (__cdecl *)(const __int64 &)>::make(const A &)'	fixed_point	f:\mtsbx\fp\fp.hpp	192	
Error	C2677	binary '<<': no global operator found which takes type 'std::integral_constant<__int64,0>' (or there is no acceptable conversion)	fixed_point	f:\mtsbx\fp\fp.hpp	68	
Error	C3313	'z': variable cannot have the type 'void'	fixed_point	f:\mtsbx\fixed_point\fixed_point\main.cpp	20	
Error	C3536	'z': cannot be used before it is initialized	fixed_point	f:\mtsbx\fixed_point\fixed_point\main.cpp	21	
Error	C2512	'std::is_integral<_Ty>': no appropriate default constructor available	fixed_point	f:\mtsbx\fp\fp.hpp	43	
Error	C2512	'std::is_floating_point<_Ty>': no appropriate default constructor available	fixed_point	f:\mtsbx\fp\fp.hpp	47	
Error	C2784	'std::basic_ostream<_Elem,_Traits> &std::operator <<(std::basic_ostream<_Elem,_Traits> &,_Elem)': could not deduce template argument for 'std::basic_ostream<_Elem,_Traits> &' from 'int64_t (__cdecl *const )(const __int64 &)'	fixed_point	f:\mtsbx\fp\fp.hpp	68	
Error	C2784	'std::basic_ostream<_Elem,_Traits> &std::operator <<(std::basic_ostream<_Elem,_Traits> &,const _Elem *)': could not deduce template argument for 'std::basic_ostream<_Elem,_Traits> &' from 'int64_t (__cdecl *const )(const __int64 &)'	fixed_point	f:\mtsbx\fp\fp.hpp	68	
Error	C2784	'std::basic_ostream<_Elem,_Traits> &std::operator <<(std::basic_ostream<_Elem,_Traits> &,const std::_Timeobj<_Elem2,const tm*> &)': could not deduce template argument for 'std::basic_ostream<_Elem,_Traits> &' from 'int64_t (__cdecl *const )(const __int64 &)'	fixed_point	f:\mtsbx\fp\fp.hpp	68	
Error	C2784	'std::basic_ostream<_Elem,_Traits> &std::operator <<(std::basic_ostream<_Elem,_Traits> &,const std::_Smanip<_Arg> &)': could not deduce template argument for 'std::basic_ostream<_Elem,_Traits> &' from 'int64_t (__cdecl *const )(const __int64 &)'	fixed_point	f:\mtsbx\fp\fp.hpp	68	
Error	C2784	'std::basic_ostream<_Elem,_Traits> &std::operator <<(std::basic_ostream<_Elem,_Traits> &,const std::_Quote_out<_Elem,_QuTraits,_Sizet> &)': could not deduce template argument for 'std::basic_ostream<_Elem,_Traits> &' from 'int64_t (__cdecl *const )(const __int64 &)'	fixed_point	f:\mtsbx\fp\fp.hpp	68	
Error	C2784	'std::basic_ostream<_Elem,_Traits> &std::operator <<(std::basic_ostream<_Elem,_Traits> &,const std::_Quote_in<_Elem,_Traits,_Alloc> &)': could not deduce template argument for 'std::basic_ostream<_Elem,_Traits> &' from 'int64_t (__cdecl *const )(const __int64 &)'	fixed_point	f:\mtsbx\fp\fp.hpp	68	
Error	C2784	'std::basic_ostream<_Elem,_Traits> &std::operator <<(std::basic_ostream<_Elem,_Traits> &,const std::_Monobj<_Money> &)': could not deduce template argument for 'std::basic_ostream<_Elem,_Traits> &' from 'int64_t (__cdecl *const )(const __int64 &)'	fixed_point	f:\mtsbx\fp\fp.hpp	68	
Error	C2784	'std::basic_ostream<_Elem,_Traits> &std::operator <<(std::basic_ostream<_Elem,_Traits> &,const std::_Fillobj<_Elem2> &)': could not deduce template argument for 'std::basic_ostream<_Elem,_Traits> &' from 'int64_t (__cdecl *const )(const __int64 &)'	fixed_point	f:\mtsbx\fp\fp.hpp	68	
Error	C2784	'std::basic_ostream<_Elem,_Traits> &std::operator <<(std::basic_ostream<_Elem,_Traits> &,const std::shared_ptr<_Ty> &)': could not deduce template argument for 'std::basic_ostream<_Elem,_Traits> &' from 'int64_t (__cdecl *const )(const __int64 &)'	fixed_point	f:\mtsbx\fp\fp.hpp	68	
Error	C2784	'std::basic_ostream<_Elem,_Traits> &std::operator <<(std::basic_ostream<_Elem,_Traits> &,const std::error_code &)': could not deduce template argument for 'std::basic_ostream<_Elem,_Traits> &' from 'int64_t (__cdecl *const )(const __int64 &)'	fixed_point	f:\mtsbx\fp\fp.hpp	68	
Error	C2784	'std::basic_ostream<_Elem,_Traits> &std::operator <<(std::basic_ostream<_Elem,_Traits> &,const std::basic_string<_Elem,_Traits,_Alloc> &)': could not deduce template argument for 'std::basic_ostream<_Elem,_Traits> &' from 'int64_t (__cdecl *const )(const __int64 &)'	fixed_point	f:\mtsbx\fp\fp.hpp	68	
Error	C2784	'std::basic_ostream<_Elem,_Traits> &std::operator <<(std::basic_ostream<_Elem,_Traits> &,const char *)': could not deduce template argument for 'std::basic_ostream<_Elem,_Traits> &' from 'int64_t (__cdecl *const )(const __int64 &)'	fixed_point	f:\mtsbx\fp\fp.hpp	68	
Error	C2784	'std::basic_ostream<_Elem,_Traits> &std::operator <<(std::basic_ostream<_Elem,_Traits> &,char)': could not deduce template argument for 'std::basic_ostream<_Elem,_Traits> &' from 'int64_t (__cdecl *const )(const __int64 &)'	fixed_point	f:\mtsbx\fp\fp.hpp	68	
Error	C2784	'std::basic_ostream<_Elem,_Traits> &std::operator <<(std::basic_ostream<_Elem,_Traits> &&,const _Ty &)': could not deduce template argument for 'std::basic_ostream<_Elem,_Traits> &&' from 'int64_t (__cdecl *const )(const __int64 &)'	fixed_point	f:\mtsbx\fp\fp.hpp	68	
Error	C2784	'std::basic_ostream<_Elem,_Tr> &std::operator <<(std::basic_ostream<_Elem,_Tr> &,const std::complex<_Other> &)': could not deduce template argument for 'std::basic_ostream<_Elem,_Tr> &' from 'int64_t (__cdecl *const )(const __int64 &)'	fixed_point	f:\mtsbx\fp\fp.hpp	68	
Error	C2784	'std::basic_ostream<char,_Traits> &std::operator <<(std::basic_ostream<char,_Traits> &,unsigned char)': could not deduce template argument for 'std::basic_ostream<char,_Traits> &' from 'int64_t (__cdecl *const )(const __int64 &)'	fixed_point	f:\mtsbx\fp\fp.hpp	68	
Error	C2784	'std::basic_ostream<char,_Traits> &std::operator <<(std::basic_ostream<char,_Traits> &,signed char)': could not deduce template argument for 'std::basic_ostream<char,_Traits> &' from 'int64_t (__cdecl *const )(const __int64 &)'	fixed_point	f:\mtsbx\fp\fp.hpp	68	
Error	C2784	'std::basic_ostream<char,_Traits> &std::operator <<(std::basic_ostream<char,_Traits> &,const unsigned char *)': could not deduce template argument for 'std::basic_ostream<char,_Traits> &' from 'int64_t (__cdecl *const )(const __int64 &)'	fixed_point	f:\mtsbx\fp\fp.hpp	68	
Error	C2784	'std::basic_ostream<char,_Traits> &std::operator <<(std::basic_ostream<char,_Traits> &,const signed char *)': could not deduce template argument for 'std::basic_ostream<char,_Traits> &' from 'int64_t (__cdecl *const )(const __int64 &)'	fixed_point	f:\mtsbx\fp\fp.hpp	68	
Error	C2784	'std::basic_ostream<char,_Traits> &std::operator <<(std::basic_ostream<char,_Traits> &,const char *)': could not deduce template argument for 'std::basic_ostream<char,_Traits> &' from 'int64_t (__cdecl *const )(const __int64 &)'	fixed_point	f:\mtsbx\fp\fp.hpp	68	
Error	C2784	'std::basic_ostream<char,_Traits> &std::operator <<(std::basic_ostream<char,_Traits> &,char)': could not deduce template argument for 'std::basic_ostream<char,_Traits> &' from 'int64_t (__cdecl *const )(const __int64 &)'	fixed_point	f:\mtsbx\fp\fp.hpp	68	
Error	C2672	'operator __surrogate_func': no matching overloaded function found	fixed_point	f:\mtsbx\fp\fp.hpp	183	
Warning	C4244	'initializing': conversion from 'double' to 'const int64_t', possible loss of data	fixed_point	f:\mtsbx\fp\fp.hpp	40	
Error	C2512	'fp::is_fp<B>': no appropriate default constructor available	fixed_point	f:\mtsbx\fp\fp.hpp	98	
Error	C2512	'fp::is_fp<B>': no appropriate default constructor available	fixed_point	f:\mtsbx\fp\fp.hpp	102	
Error	C2672	'fp::fp_t<int64_t,32,A (__cdecl *)(const __int64 &)>::make': no matching overloaded function found	fixed_point	f:\mtsbx\fp\fp.hpp	190	
Error	C2535	'fp::fp_t<int64_t,32,A (__cdecl *)(const __int64 &)>::fp_t(const B &,enable_if<_Test,_Ty>::type *)': member function already defined or declared	fixed_point	f:\mtsbx\fp\fp.hpp	102	
Error	C2572	'fp::fp_t<int64_t,32,A (__cdecl *)(const __int64 &)>::fp_t': redefinition of default argument: parameter 1	fixed_point	f:\mtsbx\fp\fp.hpp	102	
Error	C2783	'auto fp::operators::operator <<(const T &,const std::integral_constant<B,V> &)': could not deduce template argument for '<unnamed-symbol>'	fixed_point	f:\mtsbx\fp\fp.hpp	68	
Error	C2995	'auto fp::detail::builtin_const_shift(const enable_if<_Test,T>::type &)': function template has already been defined	fixed_point	f:\mtsbx\fp\fp.hpp	49

**Comment by mizvekov** [comment]
Hello,
I haven't tried to compile this in visual studio in ages, when I originally wrote this back 4 years ago, only clang was standards compliant enough to come close to building this.
Things might have improved, could be possible now. I will take a look.

**Comment by RallyTronics** [comment]
I would appreciate that!

**Comment by mizvekov** [comment]
I just submitted an update that works around some MSVC bugs. That should be enough to get your example working on MSVC 15.7.

It's not a total fix yet, it still fails to compile some tests. But I believe these are problems in the test code not in the library itself.

Since I think this fixes this particular issue, I'm closing it.

If you find any other problems feel free to open another issue.

**Comment by RallyTronics** [comment]
Thanks, I appreciate it!
